### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Raynos** [uber/build-changelog#2]
## Todo
- [x] check whether shrinkwrap.json exists
- [x] support different git log commands
- [x] support major flag
- [ ] support tree view in changelog
- [ ] make commit shas optional
- [x] write more docs
- [ ] make the date format configurable
